name: Sync Google Sheet to JSON

on:
  schedule:
    - cron: "0 0 * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install pandas requests python-slugify

      - name: Download Google Sheet and merge with JSON
        run: |
          python sync.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update JSON and assets from Google Sheet" || echo "No changes"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/ezeanyimhenry/igbo-cosmology.git HEAD:main
